---
title: "Untitled"
output: html_document
---


"All"="55235681_55378697", "2DL4-3DL1"= "55314840_55378569", "2DL4-3DL2"= "55314840_55378697"
"All"="55235681_55378697", "3DL3-3DP1"= "55235681_55303593"

"All"="54724442_54867207", "2DL4-3DL1"= "54803610_54830778", "2DL4-3DL2"= "54803610_54867207" "3DL3-3DP1"=54724442_54790417
```{r}
mobj1 <- get(load("~/projects/KIR_Methods/model/hg38/0.01/KIR2DL3/KIR2DL3_54724442_54867207_model.RData"))
model1 <- hlaModelFromObj(mobj1)
mobj2 <- get(load("~/projects/KIR_Methods/model/hg38/0.01/KIR2DL3/KIR2DL3_54724442_54790417_model.RData"))
model2 <- hlaModelFromObj(mobj2)
#mobj3 <- get(load("~/projects/KIR_Methods/model/hg38/0.005/KIR2DS2/KIR2DS2_54803610_54867207_model.RData"))
#model3 <- hlaModelFromObj(mobj3)

summary(model1)
summary(model2)
#summary(model3)
```



```{r}
# create-model-object.R
pong2_models <- list(
  # hg19 models
  hg19 = list(
    #0.01
    allele_fileter_001=list(
      KIR2DL1 = get(load("~/projects/KIR_Methods/model/hg19/0.01/KIR2DL1/KIR2DL1_55235681_55303593_model.RData")),
      KIR2DL3 = get(load("~/projects/KIR_Methods/model/hg19/0.01/KIR2DL3/KIR2DL3_55235681_55378697_model.RData")),
      KIR2DL2 = get(load("~/projects/KIR_Methods/kir2dl2/hg19/0.01/KIR2DL2/KIR2DL2_55235681_55378697_model.RData")),
      KIR2DL4 = get(load("~/projects/KIR_Methods/model/hg19/0.01/KIR2DL4/KIR2DL4_55235681_55378697_model.RData")),
      KIR3DL1 = get(load("~/projects/KIR_Methods/model/hg19/0.01/KIR3DL1/KIR3DL1_55235681_55378697_model.RData")),
      KIR3DL2 = get(load("~/projects/KIR_Methods/model/hg19/0.01/KIR3DL2/KIR3DL2_55235681_55378697_model.RData")),
      KIR2DS4 = get(load("~/projects/KIR_Methods/model/hg19/0.01/KIR2DS4/KIR2DS4_55235681_55378697_model.RData")),
      KIR2DS2 = get(load("~/projects/KIR_Methods/model/hg19/0.01/KIR2DS2/KIR2DS2_55235681_55303593_model.RData")),
      KIR2DS1 = get(load("~/projects/KIR_Methods/model/hg19/0.01/KIR2DS1/KIR2DS1_55314840_55378569_model.RData")),
      KIR2DS5 = get(load("~/projects/KIR_Methods/model/hg19/0.01/KIR2DS5/KIR2DS5_55235681_55378697_model.RData"))
    ),
    #0.005
    allele_fileter_0005=list(
      KIR2DL1 = get(load("~/projects/KIR_Methods/model/hg19/0.005/KIR2DL1/KIR2DL1_55235681_55378697_model.RData")),
      KIR2DL3 = get(load("~/projects/KIR_Methods/model/hg19/0.005/KIR2DL3/KIR2DL3_55235681_55303593_model.RData")),
      KIR2DL4 = get(load("~/projects/KIR_Methods/model/hg19/0.005/KIR2DL4/KIR2DL4_55235681_55378697_model.RData")),
      KIR3DL1 = get(load("~/projects/KIR_Methods/model/hg19/0.005/KIR3DL1/KIR3DL1_55314840_55378569_model.RData")),
      KIR3DL2 = get(load("~/projects/KIR_Methods/model/hg19/0.005/KIR3DL2/KIR3DL2_55314840_55378569_model.RData")),
      KIR2DS4 = get(load("~/projects/KIR_Methods/model/hg19/0.005/KIR2DS4/KIR2DS4_55314840_55378569_model.RData")),
      KIR2DS2 = get(load("~/projects/KIR_Methods/model/hg19/0.005/KIR2DS2/KIR2DS2_55235681_55303593_model.RData")),
      KIR2DS1 = get(load("~/projects/KIR_Methods/model/hg19/0.005/KIR2DS1/KIR2DS1_55314840_55378697_model.RData")),
      KIR2DS5 = get(load("~/projects/KIR_Methods/model/hg19/0.005/KIR2DS5/KIR2DS5_55235681_55378697_model.RData"))
    )
  ),
  
  # hg 38 models
  hg38 = list(
    #0.00
    allele_fileter_00=list(
      KIR3DL1 = get(load("~/projects/KIR_Methods/unfiltered_kir3dl1/hg38/0/KIR3DL1/KIR3DL1_54803610_54867207_model.RData")),
      KIR3DL1S1 = get(load("~/projects/KIR_Methods/kir3dl1s1/hg38/0/KIR3DL1S1/KIR3DL1S1_54724442_54867207_model.RData")),
      KIR3DS1 = get(load("~/projects/KIR_Methods/kir3dl1s1/hg38/0/KIR3DS1/KIR3DS1_54724442_54867207_model.RData")),
      KIR3DL2 = get(load("~/projects/KIR_Methods/unfiltered_kir3dl2/hg38/0/KIR3DL2/KIR3DL2_54803610_54867207_model.RData")),
      KIR2DL2 = get(load("~/projects/KIR_Methods/kir2dl23/hg38/0/KIR2DL2/KIR2DL2_54724442_54790417_model.RData")),
      KIR2DL23 = get(load("~/projects/KIR_Methods/kir2dl23/hg38/0/KIR2DL23/KIR2DL23_54724442_54790417_model.RData"))
    ),
    #0.01
    allele_fileter_001=list(
      KIR2DL1 = get(load("~/projects/KIR_Methods/model/hg38/0.01/KIR2DL1/KIR2DL1_54724442_54867207_model.RData")),
      KIR2DL3 = get(load("~/projects/KIR_Methods/model/hg38/0.01/KIR2DL3/KIR2DL3_54724442_54790417_model.RData")),
      KIR2DL2 = get(load("~/projects/KIR_Methods/kir2dl2/hg38/0.01/KIR2DL2/KIR2DL2_54724442_54790417_model.RData")),
      KIR2DL4 = get(load("~/projects/KIR_Methods/model/hg38/0.01/KIR2DL4/KIR2DL4_54724442_54867207_model.RData")),
      KIR3DL1 = get(load("~/projects/KIR_Methods/model/hg38/0.01/KIR3DL1/KIR3DL1_54803610_54867207_model.RData")),
      KIR3DL2 = get(load("~/projects/KIR_Methods/model/hg38/0.01/KIR3DL2/KIR3DL2_54803610_54867207_model.RData")),
      KIR2DS4 = get(load("~/projects/KIR_Methods/model/hg38/0.01/KIR2DS4/KIR2DS4_54803610_54867207_model.RData")),
      KIR2DS2 = get(load("~/projects/KIR_Methods/model/hg38/0.01/KIR2DS2/KIR2DS2_54724442_54790417_model.RData")),
      KIR2DS1 = get(load("~/projects/KIR_Methods/model/hg38/0.01/KIR2DS1/KIR2DS1_54724442_54867207_model.RData")),
      KIR2DS5 = get(load("~/projects/KIR_Methods/model/hg38/0.01/KIR2DS5/KIR2DS5_54724442_54867207_model.RData"))
    ),
    #0.005
    allele_fileter_0005=list(
      KIR2DL1 = get(load("~/projects/KIR_Methods/model/hg38/0.005/KIR2DL1/KIR2DL1_54724442_54867207_model.RData")),
      KIR2DL3 = get(load("~/projects/KIR_Methods/model/hg38/0.005/KIR2DL3/KIR2DL3_54724442_54790417_model.RData")),
      KIR2DL4 = get(load("~/projects/KIR_Methods/model/hg38/0.005/KIR2DL4/KIR2DL4_54724442_54867207_model.RData")),
      KIR3DL1 = get(load("~/projects/KIR_Methods/model/hg38/0.005/KIR3DL1/KIR3DL1_54803610_54867207_model.RData")),
      KIR3DL2 = get(load("~/projects/KIR_Methods/model/hg38/0.005/KIR3DL2/KIR3DL2_54803610_54867207_model.RData")),
      KIR2DS4 = get(load("~/projects/KIR_Methods/model/hg38/0.005/KIR2DS4/KIR2DS4_54803610_54867207_model.RData")),
      KIR2DS2 = get(load("~/projects/KIR_Methods/model/hg38/0.005/KIR2DS2/KIR2DS2_54724442_54790417_model.RData")),
      KIR2DS1 = get(load("~/projects/KIR_Methods/model/hg38/0.005/KIR2DS1/KIR2DS1_54724442_54867207_model.RData")),
      KIR2DS5 = get(load("~/projects/KIR_Methods/model/hg38/0.005/KIR2DS5/KIR2DS5_54724442_54867207_model.RData")),
      KIR3DL1S1 = get(load("~/projects/KIR_Methods/kir3dl1s1/hg38/0/KIR3DL1S1/KIR3DL1S1_54724442_54867207_model.RData")),
      KIR3DS1 = get(load("~/projects/KIR_Methods/kir3dl1s1/hg38/0/KIR3DS1/KIR3DS1_54724442_54867207_model.RData")),
      KIR2DL2 = get(load("~/projects/KIR_Methods/kir2dl23/hg38/0/KIR2DL2/KIR2DL2_54724442_54790417_model.RData")),
      KIR2DL23 = get(load("~/projects/KIR_Methods/kir2dl23/hg38/0/KIR2DL23/KIR2DL23_54724442_54790417_model.RData"))
    )
  )
)


# Optional: Add metadata / version info (good practice)
attr(pong2_models, "version") <- "1.0.0"
attr(pong2_models, "date")    <- Sys.Date()
attr(pong2_models, "description") <- "Pre-trained KIR prediction models for PONG2 package"

# Save as single file (use compress = "xz" for best size reduction)
save(pong2_models, file = "../../../data/models.rda", compress = "xz")
```

